openapi: 3.0.0
info:
  version: "v1"
  title: WSO2 Identity Server QRCode-Based Authentication Rest API
  description: |
    This document specifies  **RESTfulAPIs** for WSO2 **Identity Server - QRCode-based Authentication**.
    It is written with [openapi:3.0.0](http://swagger.io/).
  contact:
    name: WSO2 Identity Server
    url: "http://wso2.com/identity-server/"
    email: iam-dev@wso2.org
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
  - url: https://{host}/t/{tenant_context}/api/users/v1

security:
  - bearerAuth: []

paths:
  /me/qr-auth/authenticate:
    post:
      description: |
        This API is used to authenticate a user.<br/>
      summary: |
        Authenticate user.
      requestBody:
        description: Request sent for user registration.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDataDTO'
      responses:
        201:
          description: Authenticated the user
          headers:
            location:
              description: URI of the authenticated user
              schema:
                type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
      tags:
        - me
        
components:
  schemas:
    AuthDataDTO:
      type: object
      description: User authentication information
      properties:
        sessionDataKey:
          description: SessionDataKey
          type: string
          example: b03f90c9-6723-48f6-863b-a35f1ac77f57
        tenantDomain:
          description: Tenant domain
          type: string
          example: photogallery.com
        clientID:
          description: Client ID
          type: string
          example: A9qHTjNwUOAifHqCdfcvwLYfslYa

    ErrorDTO:
      type: object
      description: Model for error codes
      properties:
        code:
          type: string
          example: PDM-15001
        message:
          type: string
          example: An error occurred...
        description:
          type: string
          example: The error occurred due to...
        traceId:
          type: string
          example: b03f90c9-6723-48f6-863b-a35f1ac77f57

  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
